repos:
  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black
        args: [--target-version, py311]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: ""
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.7.1
