version: "3"

services:
  engine:
    build:
      context: .
      dockerfile: ./engine/Dockerfile
    environment:
      XDG_RUNTIME_DIR: /app
    image: hxtts:latest
    network_mode: host
    privileged: true
    restart: unless-stopped
    stop_signal: SIGKILL
    volumes:
      - /run/user/1000/pipewire-0:/app/pipewire-0

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./overlay:/usr/share/nginx/html:ro
