version: "3"

services:
  engine:
    build:
      context: .
      dockerfile: ./engine/Dockerfile
    environment:
      PULSE_SERVER: unix:/tmp/pulseaudio.socket
      PULSE_COOKIE: /tmp/pulseaudio.cookie
    image: hxtts:latest
    network_mode: host
    privileged: true
    restart: unless-stopped
    stop_signal: SIGKILL
    tty: true
    volumes:
      - /dev/snd:/dev/snd
      - /tmp/pulseaudio.socket:/tmp/pulseaudio.socket

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./overlay:/usr/share/nginx/html:ro
